# Node.jsのイメージを使用
FROM node:23.6

# プロキシ設定
ENV http_proxy=http://proxy50.adm.toyota.co.jp:15520
ENV https_proxy=http://proxy50.adm.toyota.co.jp:15520

# wx Library
RUN mkdir -p /root/.config/pip
RUN echo "[global]" > /root/.config/pip/pip.conf
RUN echo "proxy = http://proxy50.adm.toyota.co.jp:15520" >> /root/.config/pip/pip.conf
RUN echo "Acquire::http::proxy \"http://proxy50.adm.toyota.co.jp:15520\";" >> /etc/apt/apt.conf
RUN echo "Acquire::https::proxy \"http://proxy50.adm.toyota.co.jp:15520\";" >> /etc/apt/apt.conf
RUN cat /etc/resolv.conf

# システムの更新とpingコマンドのインストール

RUN rm -rf /var/lib/apt/lists/*
RUN echo "[global]" > /root/.config/pip/pip.conf
RUN echo "proxy = http://proxy50.adm.toyota.co.jp:15520" >> /root/.config/pip/pip.conf
RUN echo "http_proxy=http://proxy50.adm.toyota.co.jp:15520" >> /etc/wgetrc
RUN echo "https_proxy=http://proxy50.adm.toyota.co.jp:15520" >> /etc/wgetrc

RUN rm -f /etc/apt/apt.conf.d/*

RUN npm config set proxy http://proxy50.adm.toyota.co.jp:15520
RUN npm config set https-proxy http://proxy50.adm.toyota.co.jp:15520


# 作業ディレクトリを設定
WORKDIR /app

# 必要なツールをインストール
RUN apt-get update && apt-get install -y iputils-ping traceroute

COPY ../src .

RUN rm -rf .nuxt node_modules && npm install

EXPOSE 3000
EXPOSE 3001

# タイムゾーンを東京に設定
ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# プロキシ設定を解除
ENV http_proxy=""
ENV https_proxy=""

# bashシェルを起動
CMD ["/bin/bash"]